services:
  single:
    build:
      context: .
      dockerfile: docker/single.Dockerfile
    environment:
      - MB_RECHECK_HOURS=72
      - DATABASE_URL=file:/app/data/app.db
      - YA_PYPROXY_URL=http://localhost:8080
      - QBT_URL=http://94.41.86.101:9097
      - QBT_USER=admin
      - QBT_PASS=adminadmin
      - QBT_DELETE_FILES=true
      - PORT=3000
      - PORT_API=4000
      - LOG_LEVEL=debug       # |info|warn|error|fatal|all|off
      - LOG_TO_FILES=1        # включить запись в файлы
      - LOG_DIR=/data/log/app  # каталог (дефолт /var/log/app)
      - OG_MAX_SIZE=50M       # размер одного файла до ротации
      - LOG_BACKUPS=14        # сколько бэкапов хранить/чистить
    #      - LOG_DATE_PATTERN=yyyy-MM-dd — суффикс дневных файлов
    volumes:
      - ./data:/app/data
    ports:
      - '4000:4000'
      - '3000:3000'
      - '8080:8080'
    healthcheck:
      test: ['CMD', 'wget', '-qO-', 'http://localhost:4000/health']
      interval: 10s
      timeout: 3s
      retries: 5
