-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_Setting" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT DEFAULT 1,
    "lidarrAllowNoMetadata" BOOLEAN NOT NULL DEFAULT false,
    "backupEnabled" BOOLEAN NOT NULL DEFAULT false,
    "backupCron" TEXT,
    "backupRetention" INTEGER DEFAULT 14,
    "backupDir" TEXT,
    "notifyType" TEXT NOT NULL DEFAULT 'none',
    "telegramBot" TEXT,
    "telegramChatId" TEXT,
    "webhookUrl" TEXT,
    "webhookSecret" TEXT,
    "yandexDriver" TEXT NOT NULL DEFAULT 'pyproxy',
    "pyproxyUrl" TEXT,
    "yandexToken" TEXT,
    "lidarrUrl" TEXT,
    "lidarrApiKey" TEXT,
    "mode" TEXT NOT NULL DEFAULT 'artists',
    "pushTarget" TEXT NOT NULL DEFAULT 'artists',
    "enableExport" BOOLEAN NOT NULL DEFAULT true,
    "enablePush" BOOLEAN NOT NULL DEFAULT false,
    "exportPath" TEXT,
    "rootFolderPath" TEXT,
    "qualityProfileId" INTEGER,
    "metadataProfileId" INTEGER,
    "monitor" TEXT,
    "cronYandex" TEXT NOT NULL DEFAULT '0 */6 * * *',
    "cronLidarr" TEXT NOT NULL DEFAULT '0 3 * * *',
    "yandexCron" TEXT,
    "lidarrCron" TEXT,
    "cronCustomMatch" TEXT NOT NULL DEFAULT '0 0 * * *',
    "cronCustomPush" TEXT NOT NULL DEFAULT '0 12 * * *',
    "cronYandexPull" TEXT NOT NULL DEFAULT '0 */6 * * *',
    "cronYandexMatch" TEXT NOT NULL DEFAULT '10 */6 * * *',
    "cronYandexPush" TEXT NOT NULL DEFAULT '45 */6 * * *',
    "yandexMatchTarget" TEXT NOT NULL DEFAULT 'both',
    "yandexPushTarget" TEXT NOT NULL DEFAULT 'both',
    "cronLidarrPull" TEXT NOT NULL DEFAULT '0 3 * * *',
    "lidarrPullTarget" TEXT NOT NULL DEFAULT 'both',
    "enableCronYandexPull" BOOLEAN NOT NULL DEFAULT true,
    "enableCronYandexMatch" BOOLEAN NOT NULL DEFAULT true,
    "enableCronYandexPush" BOOLEAN NOT NULL DEFAULT true,
    "enableCronCustomMatch" BOOLEAN NOT NULL DEFAULT true,
    "enableCronCustomPush" BOOLEAN NOT NULL DEFAULT true,
    "enableCronLidarrPull" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "matchRetryDays" INTEGER NOT NULL DEFAULT 3,
    "allowRepush" BOOLEAN NOT NULL DEFAULT false,
    "qbtUrl" TEXT,
    "qbtUser" TEXT,
    "qbtPass" TEXT,
    "qbtDeleteFiles" BOOLEAN NOT NULL DEFAULT true,
    "qbtWebhookSecret" TEXT
);
INSERT INTO "new_Setting" ("allowRepush", "backupCron", "backupDir", "backupEnabled", "backupRetention", "createdAt", "cronCustomMatch", "cronCustomPush", "cronLidarr", "cronLidarrPull", "cronYandex", "cronYandexMatch", "cronYandexPull", "cronYandexPush", "enableCronCustomMatch", "enableCronCustomPush", "enableCronLidarrPull", "enableCronYandexMatch", "enableCronYandexPull", "enableCronYandexPush", "enableExport", "enablePush", "exportPath", "id", "lidarrAllowNoMetadata", "lidarrApiKey", "lidarrCron", "lidarrPullTarget", "lidarrUrl", "matchRetryDays", "metadataProfileId", "mode", "monitor", "notifyType", "pushTarget", "pyproxyUrl", "qualityProfileId", "rootFolderPath", "telegramBot", "telegramChatId", "updatedAt", "webhookSecret", "webhookUrl", "yandexCron", "yandexDriver", "yandexMatchTarget", "yandexPushTarget", "yandexToken") SELECT "allowRepush", "backupCron", "backupDir", "backupEnabled", "backupRetention", "createdAt", "cronCustomMatch", "cronCustomPush", "cronLidarr", "cronLidarrPull", "cronYandex", "cronYandexMatch", "cronYandexPull", "cronYandexPush", "enableCronCustomMatch", "enableCronCustomPush", "enableCronLidarrPull", "enableCronYandexMatch", "enableCronYandexPull", "enableCronYandexPush", "enableExport", "enablePush", "exportPath", "id", "lidarrAllowNoMetadata", "lidarrApiKey", "lidarrCron", "lidarrPullTarget", "lidarrUrl", "matchRetryDays", "metadataProfileId", "mode", "monitor", "notifyType", "pushTarget", "pyproxyUrl", "qualityProfileId", "rootFolderPath", "telegramBot", "telegramChatId", "updatedAt", "webhookSecret", "webhookUrl", "yandexCron", "yandexDriver", "yandexMatchTarget", "yandexPushTarget", "yandexToken" FROM "Setting";
DROP TABLE "Setting";
ALTER TABLE "new_Setting" RENAME TO "Setting";
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
