name: CI (tests)

permissions:
  contents: read

on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch:

env:
  NODE_VERSION: "20"

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Install, Build & Test
    runs-on: ubuntu-latest
    environment: ym2lidarr
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install deps (root + workspaces)
        run: npm ci

      - name: Prisma generate (apps/api)
        run: npx -w apps/api prisma generate --schema ../../prisma/schema.prisma

      - name: Build API
        run: npm --workspace apps/api run build --if-present

      - name: Build Web
        run: npm --workspace apps/web run build --if-present

      - name: Run tests
        run: npm test --workspaces --if-present
