name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  DOCKERHUB_NS: ${{ vars.DOCKERHUB_NS }}

permissions:
  contents: read
  packages: write

concurrency:
  group: release-${{ github.event.release.tag_name || github.ref }}
  cancel-in-progress: false

jobs:
  build_all:
    name: Build all images (no push)
    runs-on: ubuntu-latest
    environment: ym2lidarr
    strategy:
      fail-fast: false
      matrix:
        target:
          - { name: "api",    dockerfile: "./docker/api.Dockerfile",    repo: "ym2lidarr-api" }
          - { name: "web",    dockerfile: "./docker/web.Dockerfile",    repo: "ym2lidarr-web" }
          - { name: "pyproxy",dockerfile: "./docker/pyproxy.Dockerfile",repo: "ym2lidarr-pyproxy" }
          - { name: "single", dockerfile: "./docker/single.Dockerfile", repo: "ym2lidarr-single" }
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
        with: { fetch-depth: 0 }

      - uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392
      - uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435

      - name: Build ${{ matrix.target.name }} (no push)
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          context: .
          file: ./${{ matrix.target.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: false
          tags: dummy/${{ matrix.target.repo }}:${{ github.event.release.tag_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  push_all:
    name: Push all images (from release tag)
    runs-on: ubuntu-latest
    environment: ym2lidarr
    needs: build_all
    strategy:
      fail-fast: false
      matrix:
        target:
          - { name: "api",    dockerfile: "./docker/api.Dockerfile",    repo: "ym2lidarr-api" }
          - { name: "web",    dockerfile: "./docker/web.Dockerfile",    repo: "ym2lidarr-web" }
          - { name: "pyproxy",dockerfile: "./docker/pyproxy.Dockerfile",repo: "ym2lidarr-pyproxy" }
          - { name: "single", dockerfile: "./docker/single.Dockerfile", repo: "ym2lidarr-single" }

    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
        with: { fetch-depth: 0 }

      - uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392
      - uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435

      - name: Login to Docker Hub
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta (${{ matrix.target.name }})
        id: meta
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f
        env:
          IMAGE: ${{ env.DOCKERHUB_NS }}/${{ matrix.target.repo }}
        with:
          images: ${{ env.IMAGE }}
          tags: |
            type=semver,pattern={{version}},value=${{ github.event.release.tag_name }}
            type=semver,pattern={{major}}.{{minor}},value=${{ github.event.release.tag_name }}
            type=semver,pattern={{major}},value=${{ github.event.release.tag_name }}
            type=raw,value=latest

      - name: Build & Push ${{ matrix.target.name }}
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          context: .
          file: ./${{ matrix.target.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
